"""AI Care Coordinator demo API.

Each visitor gets their own demo state, keyed by the X-Session-Id header (the
UI generates a random id and keeps it in localStorage). State lives in memory
and resets when the server restarts.
"""
import io
import json
import logging
import re
import threading
import time
from collections import OrderedDict

from dotenv import load_dotenv

load_dotenv()

from fastapi import FastAPI, File, Header, HTTPException, UploadFile  # noqa: E402
from fastapi.middleware.cors import CORSMiddleware  # noqa: E402
from pydantic import BaseModel  # noqa: E402

from . import demo_data as D  # noqa: E402
from . import fhir_data, llm  # noqa: E402

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("care")

app = FastAPI(title="AI Care Coordinator API", version="0.1.0",
              description="Demo backend. All people, providers, prices and plan details are sample data.")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# ---------- per-visitor state ----------

MAX_SESSIONS = 1000
MAX_DOC_CHARS = 30000
_sessions: OrderedDict[str, dict] = OrderedDict()
_lock = threading.Lock()


def _fresh() -> dict:
    return {
        "account": {"name": "Maya Chen", "dob": "1991-03-04", "email": "maya.chen@example.com", "phone": "(555) 014-2291"},
        "links": {"plan": False, "portal": False},
        "authorizedRep": False,
        "ptApprovedAt": None,
        "autoApprove": False,
        "docs": [dict(d) for d in D.DEFAULT_DOCS],
        "docText": "",
        "chat": [],
    }


def session(sid: str | None) -> dict:
    sid = (sid or "default")[:64]
    with _lock:
        if sid not in _sessions:
            _sessions[sid] = _fresh()
            if len(_sessions) > MAX_SESSIONS:
                _sessions.popitem(last=False)
        _sessions.move_to_end(sid)
        return _sessions[sid]


def pt_stage(s: dict) -> int:
    """0 = needs the member's OK, 1-4 = in progress, 5 = approved and booked."""
    if s["ptApprovedAt"] is None:
        return 0
    stage = 1 + int((time.time() - s["ptApprovedAt"]) / D.PT_STEP_SECONDS)
    return 5 if stage >= 4 else stage  # the 4th step (booking) finishing means booked


# ---------- visit summary (generated once from the FHIR visit note) ----------

FALLBACK_SUMMARY = ("Your checkup looked good overall. Dr. Nair wants fasting labs to recheck cholesterol, "
                    "a 90-day refill of your current medication, a skin check for one mole, and physical therapy for your knee.")
_visit_summary = {"text": FALLBACK_SUMMARY, "source": "fallback"}


def _generate_summary():
    result = llm.summarize_visit(fhir_data.VISIT_NOTE)
    if result:
        _visit_summary.update(text=result["summary"], source="bedrock")
        log.info("Visit summary generated by Bedrock")


@app.on_event("startup")
def _startup():
    threading.Thread(target=_generate_summary, daemon=True).start()


# ---------- general ----------

@app.get("/api/health")
def health():
    return {"ok": True, "model": llm.MODEL_ID, "visitSummary": _visit_summary["source"]}


@app.post("/api/reset")
def reset(x_session_id: str | None = Header(None)):
    s = session(x_session_id)
    s.clear()
    s.update(_fresh())
    return {"ok": True}


@app.get("/api/fhir")
def fhir_bundle():
    """The raw FHIR R4 record everything else is built from."""
    return fhir_data.BUNDLE


# ---------- 1. sign up + link accounts ----------

class Signup(BaseModel):
    name: str
    dob: str
    email: str
    phone: str | None = None


@app.post("/api/signup")
def signup(body: Signup, x_session_id: str | None = Header(None)):
    s = session(x_session_id)
    s["account"] = body.model_dump()
    return {"account": s["account"]}


@app.get("/api/plans")
def plans(q: str = ""):
    q = q.lower()
    return {"plans": [p for p in D.PLANS_DIRECTORY if q in (p["name"] + p["subtitle"]).lower()]}


@app.post("/api/card/scan")
async def scan_card(file: UploadFile | None = File(None)):
    """Accepts a card photo. The demo always returns the sample card."""
    return {"card": D.CARD}


@app.get("/api/connections")
def connections(x_session_id: str | None = Header(None)):
    s = session(x_session_id)
    found = [dict(f, linked=s["links"].get(f["id"], False)) for f in D.FOUND_FROM_CLAIMS]
    return {
        "links": s["links"],
        "authorizedRep": s["authorizedRep"],
        "sources": {k: dict(v, linked=s["links"][k]) for k, v in D.CONNECTIONS.items()},
        "foundFromClaims": found if s["links"]["plan"] else [],
        "readyToFinish": s["links"]["plan"] and s["links"]["portal"] and s["authorizedRep"],
    }


@app.post("/api/connections/{source}")
def link(source: str, x_session_id: str | None = Header(None)):
    """Simulated OAuth sign-in. In production this is the SMART on FHIR authorization-code flow."""
    if source not in D.CONNECTIONS:
        raise HTTPException(404, f"Unknown source '{source}'. Use: {', '.join(D.CONNECTIONS)}")
    s = session(x_session_id)
    s["links"][source] = True
    return {"linked": source, "org": D.CONNECTIONS[source]["org"], "links": s["links"]}


@app.post("/api/consent/authorized-rep")
def authorize_rep(x_session_id: str | None = Header(None)):
    """Member e-signs a HIPAA authorization + authorized-representative form so the
    coordinator can call offices, talk to the plan and dispute bills for them."""
    s = session(x_session_id)
    s["authorizedRep"] = True
    return {"authorizedRep": True}


# ---------- 2. today ----------

@app.get("/api/today")
def today(x_session_id: str | None = Header(None)):
    s = session(x_session_id)
    stage = pt_stage(s)
    done = 4 if stage >= 5 else 3
    if stage >= 5:
        msg = "All 4 next steps from Dr. Nair's plan are handled. Nothing needs you right now."
    elif stage > 0:
        msg = "3 of 4 next steps are handled. I'm working on your PT approval now."
    else:
        msg = "I handled 3 of 4 next steps from Dr. Nair's plan. One needs your OK."
    upcoming = list(D.UPCOMING) + ([D.PT_UPCOMING] if stage >= 5 else [])
    upcoming.sort(key=lambda u: u["date"])
    return {
        "dateLabel": D.DEMO_TODAY_LABEL,
        "greeting": f"Good morning, {s['account']['name'].split()[0]}",
        "coordinator": {"since": "since Tuesday's physical", "message": msg, "stepsDone": done, "stepsTotal": 4,
                        "pendingApprovals": 1 if stage == 0 else 0},
        "upcoming": upcoming,
        "synced": [{"name": "Northside Health", "detail": "synced 2h ago"}, {"name": "Blue Ridge"}, {"name": "Elm St Pharmacy"}],
    }


# ---------- 3. visit summary + PT approval ----------

def _pt_step(s: dict) -> dict:
    stage = pt_stage(s)
    if stage == 0:
        status, detail = "needs_approval", "Your plan needs prior authorization. I'll ask Dr. Nair's office to submit it. Review and approve."
    elif stage < 5:
        status, detail = "in_progress", "Dr. Nair's office submitted the request. I'm tracking it with your health plan."
    else:
        status, detail = "booked", "Approved for 12 visits. First visit Tue Oct 6, 5:30 PM at Motion PT."
    return {"id": "pt", "title": "Physical therapy", "status": status, "channel": "portal_message", "detail": detail}


@app.get("/api/visits/latest")
def latest_visit(x_session_id: str | None = Header(None)):
    s = session(x_session_id)
    steps = [dict(v, id=k) for k, v in D.NEXT_STEPS.items()] + [_pt_step(s)]
    return {
        "encounterId": fhir_data.ENCOUNTER["id"],
        "title": "Annual physical",
        "provider": "Dr. Priya Nair · Primary care · Sep 22",
        "summary": _visit_summary["text"],
        "summarySource": _visit_summary["source"],
        "disclaimer": "From your after-visit notes, synced from your patient portal. I don't give medical advice. Questions about results go to Dr. Nair.",
        "stepsDone": sum(1 for st in steps if st["status"] in ("booked", "ordered")),
        "steps": steps,
    }


def _pt_view(s: dict) -> dict:
    stage = pt_stage(s)
    timeline = [dict(step, state="done" if i < stage else "busy" if i == stage and stage < 5 else "waiting")
                for i, step in enumerate(D.PT_STEPS)]
    return {
        "stage": stage,
        "status": _pt_step(s)["status"],
        "plan": [
            "Ask Dr. Nair's office to submit the prior authorization. They already have your knee notes.",
            "Track it with your health plan every 2 days, and appeal if it's denied.",
            "Book your first visit at Motion PT (in-network, 1.2 mi) once it's approved.",
        ],
        "cost": {"perVisit": 40, "visits": 12, "estimatedTotal": 480, "oopLeft": D.PLAN["outOfPocketMax"]["amount"] - D.PLAN["outOfPocketMax"]["met"]},
        "privacy": "Your request goes to Dr. Nair's office through your patient portal. The office submits it to Blue Ridge.",
        "timeline": timeline,
        "timingNote": "Demo timing is sped up. Real approvals usually take 2 to 10 business days, and I follow up every 2 days.",
    }


@app.get("/api/visits/latest/pt")
def pt_status(x_session_id: str | None = Header(None)):
    """Poll this every ~2s after approving to animate the timeline."""
    return _pt_view(session(x_session_id))


class Approve(BaseModel):
    autoApprove: bool = False


@app.post("/api/visits/latest/pt/approve")
def pt_approve(body: Approve | None = None, x_session_id: str | None = Header(None)):
    s = session(x_session_id)
    if s["ptApprovedAt"] is None:
        s["ptApprovedAt"] = time.time()
    s["autoApprove"] = bool(body and body.autoApprove)
    return _pt_view(s)


# ---------- 4. booking call ----------

@app.get("/api/calls/{call_id}")
def call(call_id: str):
    if call_id != D.CALL["id"]:
        raise HTTPException(404, "Call not found")
    return D.CALL


# ---------- 5. coverage + documents ----------

@app.get("/api/coverage")
def coverage(x_session_id: str | None = Header(None)):
    s = session(x_session_id)
    p = D.PLAN
    return {
        "plan": p["plan"], "coverage": p["coverage"], "memberId": p["memberId"],
        "meters": [
            {"label": "Deductible", "used": p["deductible"]["met"], "total": p["deductible"]["amount"],
             "text": f"${p['deductible']['met']:,} of ${p['deductible']['amount']:,}"},
            {"label": "Out-of-pocket max", "used": p["outOfPocketMax"]["met"], "total": p["outOfPocketMax"]["amount"],
             "text": f"${p['outOfPocketMax']['met']:,} of ${p['outOfPocketMax']['amount']:,}"},
            {"label": "FSA", "used": 860, "total": 1500, "text": f"${p['fsa']['balanceLeft']} left · resets Dec 31"},
        ],
        "alerts": [{
            "kind": "duplicate_charge", "title": "Caught a duplicate charge",
            "detail": "Northside Lab billed $185 twice for your Aug 14 visit. I've opened a dispute with Blue Ridge. No action needed.",
            "evidence": [e["id"] for e in fhir_data.EXPLANATIONS_OF_BENEFIT],
        }],
        "documents": [{k: v for k, v in d.items() if k != "text"} for d in s["docs"]],
    }


def _pdf_text(data: bytes) -> tuple[str, int]:
    from pypdf import PdfReader
    reader = PdfReader(io.BytesIO(data))
    out = []
    for i, page in enumerate(reader.pages[:20], 1):
        out.append(f"[page {i}] {page.extract_text() or ''}")
        if sum(map(len, out)) > MAX_DOC_CHARS:
            break
    return "\n".join(out), len(reader.pages)


@app.post("/api/documents")
async def upload(file: UploadFile = File(...), x_session_id: str | None = Header(None)):
    s = session(x_session_id)
    data = await file.read()
    if len(data) > 15 * 1024 * 1024:
        raise HTTPException(413, "File is over 15 MB")
    name = file.filename or "Document"
    ctype = file.content_type or ""
    text = ""
    if ctype == "application/pdf" or name.lower().endswith(".pdf"):
        try:
            text, pages = _pdf_text(data)
            meta = f"PDF · {pages} page{'s' if pages != 1 else ''} · read"
        except Exception:
            log.exception("PDF read failed")
            meta = "Saved · could not read the text"
    elif ctype.startswith("text/") or name.lower().endswith(".txt"):
        text = data.decode("utf-8", "ignore")[:MAX_DOC_CHARS]
        meta = "Text · read"
    else:
        meta = "Photo · saved"
    readable = len(text.strip()) > 40
    if text and not readable:
        meta = "Saved · looks scanned, could not read the text"
    if readable:
        s["docText"] = (s["docText"] + f"\n\n=== {name} ===\n{text}")[-MAX_DOC_CHARS:]
    doc = {"name": name, "meta": meta, "icon": "card" if ctype.startswith("image/") else "doc", "new": True}
    s["docs"].insert(0, doc)
    message = "Read it. Ask me anything about this plan." if readable else "Saved to your documents"
    return {"document": doc, "readable": readable, "message": message}


# ---------- 6. ask about costs ----------

CHAT_RULES = """You are the AI care coordinator in a health app. The member is {name}. Answer her questions about what care will cost, what her plan covers and how to use her benefits, using only the plan data, record and documents below. Today is Sep 25, 2026.
Rules:
- First line: the direct answer, with the dollar amount in **bold**.
- Then 2 to 4 short "- " bullets showing the math (price, deductible left, copay or coinsurance) or the key facts.
- Add a cheaper in-network option or a benefit tip when there is one. You may offer to book or remind.
- Never give medical advice or say whether she needs care. For clinical questions, say to ask Dr. Nair. For emergencies, say to call 911.
- If the data doesn't answer it, say what you'd check (for example, calling the plan) instead of guessing.
- Under 90 words. Plain text only: "- " bullets and **bold**, no headings, no tables.

PLAN DATA (JSON):
{plan}

CURRENT CARE:
{care}"""


def _chat_system(s: dict) -> str:
    stage = pt_stage(s)
    care = [f"- {v['title']}: {v['status']}. {v['detail']}" for v in D.NEXT_STEPS.values()]
    care.append(f"- Physical therapy: {_pt_step(s)['detail']}")
    system = CHAT_RULES.format(name=s["account"]["name"], plan=json.dumps(D.PLAN), care="\n".join(care))
    if stage < 5:
        system += "\n- PT is not approved yet, so don't say it's booked."
    if s["docText"]:
        system += ("\n\nTEXT FROM DOCUMENTS THE MEMBER UPLOADED (may be a real plan; prefer it over the JSON "
                   "when they conflict, and name the document):\n" + s["docText"][:24000])
    return system


def _canned(q: str) -> str:
    for pattern, answer in D.CANNED_ANSWERS:
        if re.search(pattern, q, re.I):
            return answer
    return D.CANNED_DEFAULT


def _plain(text: str) -> str:
    """Keep replies to the **bold** + "- " bullet format the UI renders."""
    text = text.replace("\u2011", "-").replace("\u2013", "-").replace("\u2014", "-").replace("\u202f", " ")
    text = re.sub(r"(?<!\*)\*(?!\*)([^*\n]+)(?<!\*)\*(?!\*)", r"\1", text)  # *italics* -> plain
    text = re.sub(r"^\s*[•*]\s+", "- ", text, flags=re.M)
    text = re.sub(r"^#+\s*", "", text, flags=re.M)
    return re.sub(r"[ \t]+$", "", text, flags=re.M).strip()


class Ask(BaseModel):
    message: str


@app.get("/api/chat")
def chat_history(x_session_id: str | None = Header(None)):
    s = session(x_session_id)
    return {"messages": s["chat"], "suggestions": D.CHAT_SUGGESTIONS}


@app.post("/api/chat")
def chat(body: Ask, x_session_id: str | None = Header(None)):
    """Reply text uses **bold** and "- " bullets (same format the demo's mdlite() renders)."""
    q = body.message.strip()[:1000]
    if not q:
        raise HTTPException(400, "Empty message")
    s = session(x_session_id)
    history = s["chat"][-8:]
    reply = llm.complete(_chat_system(s), history + [{"role": "user", "text": q}], effort="low")
    reply = _plain(reply) if reply else None
    source = "bedrock"
    if not reply:
        reply, source = _canned(q), "fallback"
    s["chat"] += [{"role": "user", "text": q}, {"role": "assistant", "text": reply}]
    return {"reply": reply, "source": source}


# ---------- 7. year in care ----------

@app.get("/api/recap")
def recap():
    return D.RECAP
